[package]
name = "graphics"
version = "0.1.0"
edition = "2024"

[dependencies]
d3d11 = { path = "../d3d11" }
common = { path = "../common" }
windows = { workspace = true }
log = { workspace = true }
anyhow = { workspace = true }
